services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: ticketpulse-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: ticketpulse-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  ticketpulse-web:
    build:
      context: .
      target: dev
    container_name: ticketpulse-web
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      KAFKA_BROKERS: kafka:9092
      AWS_REGION: ap-south-1
      AWS_SNS_TOPIC_ARN: arn:aws:sns:ap-south-1:478122456633:Ticketpulse
      AWS_SQS_QUEUE_URL: https://sqs.ap-south-1.amazonaws.com/478122456633/myqueus
    command: npm run dev -- -H 0.0.0.0 -p 3000

  ticketpulse-worker:
    build:
      context: .
      target: dev
    container_name: ticketpulse-worker
    depends_on:
      - kafka
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      KAFKA_BROKERS: kafka:9092
      AWS_REGION: ap-south-1
      AWS_SNS_TOPIC_ARN: arn:aws:sns:ap-south-1:478122456633:Ticketpulse
      AWS_SQS_QUEUE_URL: https://sqs.ap-south-1.amazonaws.com/478122456633/myqueus
    command: npm run worker
