on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSWORD }}
          port: ${{ secrets.VM_PORT }}
          script: |
            set -e

            APP_DIR="/home/rootadmin/myapp2.0"

            mkdir -p $APP_DIR

            if [ ! -d "$APP_DIR/.git" ]; then
              git clone https://github.com/shakthimonesh03-art/myapp2.0.git $APP_DIR
            fi

            cd $APP_DIR
            
            echo "Pull latest code..." 
            git fetch origin main 
            git reset --hard origin/main

            docker compose down || true
            docker compose up -d --build

            docker image prune -f
